library ieee;
  use ieee.std_logic_1164.all;

library osvvm;
  context osvvm.OsvvmContext;

library osvvm_common;
  context osvvm_common.OsvvmCommonContext;

library osvvm_spacewire;
  use osvvm_spacewire.SpaceWireTbPkg.all;
  use osvvm_spacewire.ScoreboardPkg_SpaceWire.all;
  use osvvm_spacewire.SpaceWireDsDriverPkg.all;


--------------------------------------------------------------------
-- Direct error-detection test for SpaceWireMonitor.
--
-- This test drives deliberately invalid SpaceWire Data/Strobe
-- traffic without using the SpaceWire Light spwstream core.
--
-- Error cases:
--
--   - incorrect parity for packet DATA 0x55;
--   - invalid ESC + EOP;
--   - invalid ESC + EEP;
--   - invalid ESC + ESC;
--   - Data and Strobe changing simultaneously.
--
-- Expected monitor alerts:
--
--   ERROR   = 4
--   WARNING = 1
--
-- The alerts remain enabled so that the messages generated by
-- SpaceWireMonitor are visible in the transcript.
--
-- Their counts are saved and checked before they are cleared so
-- that the deliberately generated errors do not fail the test.
--
-- After the simultaneous Data/Strobe transition, the monitor is
-- resynchronized and a valid recovery packet is checked.
--------------------------------------------------------------------
architecture Errors1 of MonitorTestCtrl is

  ------------------------------------------------------------------
  -- Direct Data/Strobe timing.
  ------------------------------------------------------------------
  constant BIT_PERIOD : time := 100 ns;


  ------------------------------------------------------------------
  -- Packet with deliberately incorrect payload parity.
  ------------------------------------------------------------------
  constant BadParityPacket : SpaceWirePacketType := (
    0 => x"55"
  );


  ------------------------------------------------------------------
  -- Valid packet sent after monitor resynchronization.
  ------------------------------------------------------------------
  constant RecoveryPacket : SpaceWirePacketType := (
    0 => x"5A"
  );


  ------------------------------------------------------------------
  -- Each packet produces one transaction per data byte and one
  -- additional transaction for its EOP terminator.
  ------------------------------------------------------------------
  constant MONITOR_TRANSACTION_COUNT : integer :=
    BadParityPacket'length + 1 +
    RecoveryPacket'length + 1;


  ------------------------------------------------------------------
  -- Expected monitor output.
  ------------------------------------------------------------------
  signal MonitorScoreboard : ScoreboardIDType;


  ------------------------------------------------------------------
  -- Indicates that the direct driver has finished sending traffic.
  ------------------------------------------------------------------
  signal DriverFinished : boolean := false;


  ------------------------------------------------------------------
  -- Barrier shared by the control, driver, and monitor checker.
  ------------------------------------------------------------------
  signal TestDone : integer_barrier := 1;


  ------------------------------------------------------------------
  -- Queue one expected packet in the passive monitor scoreboard.
  ------------------------------------------------------------------
  procedure PushExpectedPacket(
    constant Scoreboard : in ScoreboardIDType;
    constant Packet     : in SpaceWirePacketType;
    constant Ending     : in SpaceWirePacketEndType
  ) is
    variable Expected : SpaceWireStimType;
  begin

    --------------------------------------------------------------
    -- Queue every expected packet data character.
    --------------------------------------------------------------
    for Index in Packet'range loop
      Expected.Data := Packet(Index);
      Expected.Flag := (others => '0');

      Push(
        Scoreboard,
        Expected
      );
    end loop;


    --------------------------------------------------------------
    -- Queue the expected packet terminator.
    --------------------------------------------------------------
    Expected.Flag := (others => '1');

    case Ending is
      when PACKET_EOP =>
        Expected.Data := x"00";

      when PACKET_EEP =>
        Expected.Data := x"01";
    end case;

    Push(
      Scoreboard,
      Expected
    );

  end procedure PushExpectedPacket;


  ------------------------------------------------------------------
  -- Send one control character with deliberately incorrect parity.
  --
  -- SpaceWire parity for the previous symbol is transmitted as the
  -- parity bit at the beginning of the current symbol. Therefore,
  -- this procedure is used after DATA 0x55 to create a parity error
  -- for that DATA character while still transmitting a valid EOP.
  ------------------------------------------------------------------
  procedure SendControlCharacterWithBadParity(
    signal DataLine      : inout std_logic;
    signal StrobeLine    : inout std_logic;
    variable State       : inout SpaceWireDsDriverStateType;
    constant ControlCode : in std_logic_vector(1 downto 0);
    constant BitPeriod   : in time
  ) is
    variable CorrectParityBit : std_logic;
    variable BadParityBit     : std_logic;
  begin

    assert not State.ParityAlreadySent
      report
        "Errors1: bad-parity control character started while a " &
        "parity bit was already pending"
      severity failure;


    --------------------------------------------------------------
    -- Correct odd-parity value for a control character.
    --------------------------------------------------------------
    CorrectParityBit :=
      not (
        State.PreviousPayloadXor xor
        '1'
      );


    --------------------------------------------------------------
    -- Deliberately transmit the inverse.
    --------------------------------------------------------------
    BadParityBit := not CorrectParityBit;

    SendBit(
      DataLine,
      StrobeLine,
      BadParityBit,
      BitPeriod
    );


    --------------------------------------------------------------
    -- Data/control flag: one means CONTROL.
    --------------------------------------------------------------
    SendBit(
      DataLine,
      StrobeLine,
      '1',
      BitPeriod
    );


    --------------------------------------------------------------
    -- Control payload bits are transmitted LSB first.
    --------------------------------------------------------------
    SendBit(
      DataLine,
      StrobeLine,
      ControlCode(0),
      BitPeriod
    );

    SendBit(
      DataLine,
      StrobeLine,
      ControlCode(1),
      BitPeriod
    );


    --------------------------------------------------------------
    -- Keep the driver state correct for the following character.
    --------------------------------------------------------------
    State.PreviousPayloadXor :=
      ControlCode(0) xor ControlCode(1);

  end procedure SendControlCharacterWithBadParity;


  ------------------------------------------------------------------
  -- Cause an invalid physical transition by changing Data and
  -- Strobe in the same simulation event.
  ------------------------------------------------------------------
  procedure ChangeDataAndStrobeTogether(
    signal DataLine   : inout std_logic;
    signal StrobeLine : inout std_logic;
    constant Delay    : in time
  ) is
  begin
    DataLine   <= not DataLine;
    StrobeLine <= not StrobeLine;

    wait for Delay;
  end procedure ChangeDataAndStrobeTogether;

begin

  ------------------------------------------------------------------
  -- ControlProc
  --
  -- Initializes OSVVM reporting, keeps the deliberately expected
  -- monitor alerts visible, waits for the test processes, checks the
  -- alert counts and scoreboard, writes the reports, and stops.
  ------------------------------------------------------------------
  ControlProc : process

    variable MonitorID     : AlertLogIDType;
    variable MonitorAlerts : AlertCountType;

  begin

    SetTestName("TbSpaceWireMonitor_Errors1");
    SetLogEnable(PASSED, FALSE);

    MonitorScoreboard <= NewID(
      "Direct_Monitor_Error_Scoreboard"
    );

    wait for 0 ns;

    SetAlertLogOptions(
      WriteTimeLast => FALSE
    );

    SetAlertLogOptions(
      TimeJustifyAmount => 16
    );

    SetAlertLogJustify;

    wait for 0 ns;
    wait for 0 ns;

    TranscriptOpen;
    SetTranscriptMirror(TRUE);

    wait until nReset = '1';

    ClearAlerts;

    --------------------------------------------------------------
    -- Keep the expected alerts enabled so that the actual monitor
    -- messages are printed.
    --
    -- Four errors and one warning are expected. A fifth error or
    -- second warning stops the simulation.
    --------------------------------------------------------------
    MonitorID := GetAlertLogID(
      "Direct_SpaceWire_Monitor"
    );

    SetAlertStopCount(
      MonitorID,
      ERROR,
      5
    );

    SetAlertStopCount(
      MonitorID,
      WARNING,
      2
    );

    SetAlertPrintCount(
      MonitorID,
      ERROR,
      10
    );

    SetAlertPrintCount(
      MonitorID,
      WARNING,
      10
    );


    WaitForBarrier(
      TestDone,
      1 ms
    );


    --------------------------------------------------------------
    -- Save the actual monitor-alert counts while the errors and
    -- warning are still present.
    --------------------------------------------------------------
    MonitorAlerts := GetAlertCount(
      MonitorID
    );


    --------------------------------------------------------------
    -- Clear the deliberately generated alerts before the final
    -- OSVVM report. The saved counts are checked below.
    --------------------------------------------------------------
    ClearAlertCounts;


    --------------------------------------------------------------
    -- Verify all expected monitor alerts were detected.
    --------------------------------------------------------------
    AffirmIfEqual(
      MonitorAlerts(FAILURE),
      0,
      "Direct monitor expected FAILURE count"
    );

    AffirmIfEqual(
      MonitorAlerts(ERROR),
      4,
      "Direct monitor expected ERROR count"
    );

    AffirmIfEqual(
      MonitorAlerts(WARNING),
      1,
      "Direct monitor expected WARNING count"
    );


    --------------------------------------------------------------
    -- Verify all expected decoded N-Chars were received.
    --------------------------------------------------------------
    AffirmIf(
      IsEmpty(MonitorScoreboard),
      "Direct monitor error-test scoreboard is empty"
    );

    AffirmIfEqual(
      GetCheckCount(MonitorScoreboard),
      MONITOR_TRANSACTION_COUNT,
      "Direct monitor error-test scoreboard check count"
    );


    --------------------------------------------------------------
    -- Verify successful recovery after synchronization loss.
    --------------------------------------------------------------
    AffirmIf(
      Synchronized = '1',
      "Monitor resynchronized after physical transition error"
    );

    AffirmIf(
      PacketActive = '0',
      "No packet remains active after error test"
    );


    TranscriptClose;

    osvvm_spacewire.ScoreboardPkg_SpaceWire.WriteScoreboardYaml(
      FileName => "SpaceWireMonitorErrors"
    );

    EndOfTestReports(
      TimeOut => (now >= 1 ms)
    );

    std.env.stop;
    wait;

  end process ControlProc;


  ------------------------------------------------------------------
  -- DirectDriverProc
  --
  -- Generates deliberately invalid SpaceWire Data/Strobe traffic.
  ------------------------------------------------------------------
  DirectDriverProc : process

    variable DriverState : SpaceWireDsDriverStateType :=
      SPACEWIRE_DS_DRIVER_STATE_INIT;

  begin

    --------------------------------------------------------------
    -- Initialize the directly driven physical signals.
    --------------------------------------------------------------
    DataLine   <= '0';
    StrobeLine <= '0';

    wait for 0 ns;

    ResetDriver(
      DriverState
    );

    wait until nReset = '1';

    wait for 2 * BIT_PERIOD;


    --------------------------------------------------------------
    -- First NULL synchronization sequence.
    --------------------------------------------------------------
    Log(
      "DRIVER: Sending first NULL synchronization sequence",
      INFO
    );

    SendFirstNull(
      DataLine,
      StrobeLine,
      DriverState,
      BIT_PERIOD
    );


    --------------------------------------------------------------
    -- Complete another NULL after the first-NULL sequence.
    --------------------------------------------------------------
    SendNull(
      DataLine,
      StrobeLine,
      DriverState,
      BIT_PERIOD
    );

    AffirmIf(
      Synchronized = '1',
      "Monitor synchronized before error injection"
    );


    --------------------------------------------------------------
    -- Error 1:
    -- Packet 1 contains DATA 0x55 followed by an EOP whose parity
    -- bit is deliberately inverted. The monitor must report a
    -- parity error for DATA 0x55 and mark the packet parity failed.
    --------------------------------------------------------------
    Log(
      "DRIVER: Sending Packet1 with incorrect DATA parity",
      INFO
    );

    PushExpectedPacket(
      MonitorScoreboard,
      BadParityPacket,
      PACKET_EOP
    );

    SendDataCharacter(
      DataLine,
      StrobeLine,
      DriverState,
      BadParityPacket(0),
      BIT_PERIOD
    );

    SendControlCharacterWithBadParity(
      DataLine,
      StrobeLine,
      DriverState,
      SPW_CONTROL_EOP,
      BIT_PERIOD
    );


    --------------------------------------------------------------
    -- Complete the parity check for the preceding EOP.
    --------------------------------------------------------------
    SendNull(
      DataLine,
      StrobeLine,
      DriverState,
      BIT_PERIOD
    );


    --------------------------------------------------------------
    -- Error 2: invalid ESC + EOP sequence.
    --------------------------------------------------------------
    Log(
      "DRIVER: Sending invalid ESC + EOP",
      INFO
    );

    SendEsc(
      DataLine,
      StrobeLine,
      DriverState,
      BIT_PERIOD
    );

    SendEop(
      DataLine,
      StrobeLine,
      DriverState,
      BIT_PERIOD
    );

    SendNull(
      DataLine,
      StrobeLine,
      DriverState,
      BIT_PERIOD
    );


    --------------------------------------------------------------
    -- Error 3: invalid ESC + EEP sequence.
    --------------------------------------------------------------
    Log(
      "DRIVER: Sending invalid ESC + EEP",
      INFO
    );

    SendEsc(
      DataLine,
      StrobeLine,
      DriverState,
      BIT_PERIOD
    );

    SendEep(
      DataLine,
      StrobeLine,
      DriverState,
      BIT_PERIOD
    );

    SendNull(
      DataLine,
      StrobeLine,
      DriverState,
      BIT_PERIOD
    );


    --------------------------------------------------------------
    -- Error 4: invalid ESC + ESC sequence.
    --------------------------------------------------------------
    Log(
      "DRIVER: Sending invalid ESC + ESC",
      INFO
    );

    SendEsc(
      DataLine,
      StrobeLine,
      DriverState,
      BIT_PERIOD
    );

    SendEsc(
      DataLine,
      StrobeLine,
      DriverState,
      BIT_PERIOD
    );

    SendNull(
      DataLine,
      StrobeLine,
      DriverState,
      BIT_PERIOD
    );


    --------------------------------------------------------------
    -- Warning 1:
    -- Change Data and Strobe simultaneously. The monitor must lose
    -- synchronization and report a warning.
    --------------------------------------------------------------
    Log(
      "DRIVER: Changing Data and Strobe simultaneously",
      INFO
    );

    ChangeDataAndStrobeTogether(
      DataLine,
      StrobeLine,
      BIT_PERIOD
    );

    AffirmIf(
      Synchronized = '0',
      "Monitor lost synchronization after simultaneous transition"
    );


    --------------------------------------------------------------
    -- Reset the driver state and send a new first NULL.
    --------------------------------------------------------------
    ResetDriver(
      DriverState
    );

    SendFirstNull(
      DataLine,
      StrobeLine,
      DriverState,
      BIT_PERIOD
    );

    SendNull(
      DataLine,
      StrobeLine,
      DriverState,
      BIT_PERIOD
    );

    AffirmIf(
      Synchronized = '1',
      "Monitor resynchronized after new first NULL"
    );


    --------------------------------------------------------------
    -- Send one valid packet after recovery.
    --------------------------------------------------------------
    Log(
      "DRIVER: Sending valid recovery packet 5A + EOP",
      INFO
    );

    PushExpectedPacket(
      MonitorScoreboard,
      RecoveryPacket,
      PACKET_EOP
    );

    SendDataCharacter(
      DataLine,
      StrobeLine,
      DriverState,
      RecoveryPacket(0),
      BIT_PERIOD
    );

    SendEop(
      DataLine,
      StrobeLine,
      DriverState,
      BIT_PERIOD
    );


    --------------------------------------------------------------
    -- Complete the parity check for the recovery EOP.
    --------------------------------------------------------------
    SendNull(
      DataLine,
      StrobeLine,
      DriverState,
      BIT_PERIOD
    );


    --------------------------------------------------------------
    -- Allow the monitor checker to process the final events.
    --------------------------------------------------------------
    wait for 10 * BIT_PERIOD;

    DriverFinished <= true;

    WaitForBarrier(TestDone);
    wait;

  end process DirectDriverProc;


  ------------------------------------------------------------------
  -- MonitorScoreboardProc
  --
  -- Checks the decoded bad-parity packet and the valid recovery
  -- packet. Invalid ESC sequences must not emit additional N-Chars.
  ------------------------------------------------------------------
  MonitorScoreboardProc : process

    variable Actual      : SpaceWireStimType;
    variable ActualCount : natural := 0;

  begin

    wait until nReset = '1';

    loop
      wait on MonValid, DriverFinished;

      if MonValid'event and MonValid = '1' then
        Actual.Data := MonData;
        Actual.Flag := (others => MonFlag);

        Check(
          MonitorScoreboard,
          Actual
        );

        ActualCount := ActualCount + 1;
      end if;

      exit when DriverFinished and MonValid /= '1';
    end loop;


    --------------------------------------------------------------
    -- Verify the total number of monitor events.
    --------------------------------------------------------------
    AffirmIfEqual(
      ActualCount,
      MONITOR_TRANSACTION_COUNT,
      "Direct monitor error-test actual N-Char count"
    );

    WaitForBarrier(TestDone);
    wait;

  end process MonitorScoreboardProc;

end architecture Errors1;


--------------------------------------------------------------------
-- Bind the Errors1 architecture to MonitorTestCtrl_1 in the direct
-- SpaceWire monitor harness.
--------------------------------------------------------------------
configuration TbSpaceWireMonitor_Errors1 of TbSpaceWireMonitor is

  for TestHarness

    for MonitorTestCtrl_1 : MonitorTestCtrl

      use entity work.MonitorTestCtrl(Errors1);

    end for;

  end for;

end configuration TbSpaceWireMonitor_Errors1;